@echo off
echo Desktop Clock - 启动中...
echo.
echo 正在启动React开发服务器...
start cmd /k "npm start"
echo.
echo 等待React服务器启动...
timeout /t 10 /nobreak > nul
echo.
echo 正在启动Electron应用...
npm run electron-dev
pause